import type { Metadata } from 'next'
import { Crimson_Text, Geist, Geist_Mono } from 'next/font/google'

import { GrainOverlay } from '@/components/grain-overlay'
import './globals.css'

const geistSans = Geist({
	variable: '--font-sans',
	subsets: ['latin']
})

const geistMono = Geist_Mono({
	variable: '--font-mono',
	subsets: ['latin']
})

const crimsonText = Crimson_Text({
	variable: '--font-serif',
	subsets: ['latin'],
	weight: ['400', '600', '700'],
	display: 'swap'
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html
			lang="en"
			className={`dark ${geistSans.variable} ${geistMono.variable} ${crimsonText.variable} h-full antialiased`}
		>
			<body className="min-h-full flex flex-col">
				<GrainOverlay />
				{children}
			</body>
		</html>
	)
}
